import type { Bid, FraudAlert, Tender } from "./types";

export const tenders: Tender[] = [
  {
    id: "TND-1042",
    title: "National Highway Corridor Phase III",
    issuingBody: "Ministry of Road Transport",
    category: "Infrastructure",
    budget: 1840,
    budgetCurrency: "ETH",
    deadline: "2026-09-14",
    status: "Open",
    smartContractAddr: "0x8f2a4b19c7de5013aa77bf5c9d4e1a0b3c6d8e21",
    contractVerified: true,
    IPFS_CID: "bafybeigd7xk2q4mtender1042specsxq",
    riskScore: 12,
    bidCount: 14,
    description:
      "Design, build and 5-year maintenance of a 148 km six-lane corridor including 3 interchanges, smart tolling gantries and IoT structural health monitoring.",
    deliverables: [
      "Detailed project report and geotechnical survey",
      "148 km six-lane carriageway with rigid pavement",
      "3 grade-separated interchanges",
      "Smart tolling and ANPR gantry network",
      "5-year O&M with SLA-backed uptime",
    ],
    timeline: [
      { phase: "Bid window opens", date: "2026-08-01" },
      { phase: "Encrypted bid seal", date: "2026-09-14" },
      { phase: "AI risk audit", date: "2026-09-18" },
      { phase: "Allocation & payout", date: "2026-09-30" },
    ],
  },
  {
    id: "TND-2098",
    title: "Sovereign Cloud Migration & Zero-Trust Rollout",
    issuingBody: "Department of Digital Governance",
    category: "IT",
    budget: 720000,
    budgetCurrency: "USDT",
    deadline: "2026-08-29",
    status: "Auditing",
    smartContractAddr: "0x1d93ce77a4b8f0225de19c4477b0e3a5f2c91d84",
    contractVerified: true,
    IPFS_CID: "bafybeih9specsclouds2098zqmk",
    riskScore: 47,
    bidCount: 9,
    description:
      "Migration of 214 citizen-facing workloads to sovereign cloud with zero-trust identity fabric, SOC integration and post-quantum key rotation.",
    deliverables: [
      "Workload discovery and dependency mapping",
      "Landing zone with policy-as-code guardrails",
      "Zero-trust identity fabric + PAM",
      "24x7 SOC integration and runbooks",
    ],
    timeline: [
      { phase: "Bid window opens", date: "2026-07-10" },
      { phase: "Encrypted bid seal", date: "2026-08-29" },
      { phase: "AI risk audit", date: "2026-09-02" },
      { phase: "Allocation & payout", date: "2026-09-12" },
    ],
  },
  {
    id: "TND-3311",
    title: "Border Surveillance UAV Fleet Procurement",
    issuingBody: "Directorate of Defence Acquisition",
    category: "Defense",
    budget: 2960,
    budgetCurrency: "ETH",
    deadline: "2026-10-05",
    status: "Flagged",
    smartContractAddr: "0xa77b0c31e9f4d2856b13ac09e7f5d2418b6c0397",
    contractVerified: false,
    IPFS_CID: "bafybeiuavfleet3311specszz",
    riskScore: 88,
    bidCount: 6,
    description:
      "Procurement of 48 MALE-class surveillance UAVs with EO/IR payloads, encrypted datalink and in-country MRO establishment.",
    deliverables: [
      "48 airframes with EO/IR + SAR payloads",
      "Encrypted datalink & ground control stations",
      "In-country MRO facility and training",
    ],
    timeline: [
      { phase: "Bid window opens", date: "2026-08-15" },
      { phase: "Encrypted bid seal", date: "2026-10-05" },
      { phase: "AI risk audit", date: "2026-10-09" },
      { phase: "Allocation & payout", date: "2026-10-22" },
    ],
  },
  {
    id: "TND-4520",
    title: "Metro Rail Signalling CBTC Upgrade",
    issuingBody: "Metropolitan Transit Authority",
    category: "Infrastructure",
    budget: 640,
    budgetCurrency: "ETH",
    deadline: "2026-08-20",
    status: "Allocated",
    smartContractAddr: "0x3fb1908c5a2d47e6091bcd7742f0a5e3d18c9b60",
    contractVerified: true,
    IPFS_CID: "bafybeicbtcupgrade4520specs",
    riskScore: 8,
    bidCount: 11,
    description:
      "Communication-based train control upgrade across 62 km of existing metro corridor with 90-second headway target.",
    deliverables: [
      "CBTC trackside and onboard equipment",
      "Interlocking replacement at 41 stations",
      "Integrated testing and safety case",
    ],
    timeline: [
      { phase: "Bid window opens", date: "2026-06-01" },
      { phase: "Encrypted bid seal", date: "2026-08-20" },
      { phase: "AI risk audit", date: "2026-08-24" },
      { phase: "Allocation & payout", date: "2026-09-01" },
    ],
  },
  {
    id: "TND-5107",
    title: "AI Citizen Grievance Triage Platform",
    issuingBody: "Office of Public Services Reform",
    category: "IT",
    budget: 265000,
    budgetCurrency: "USDT",
    deadline: "2026-09-02",
    status: "Open",
    smartContractAddr: "0xc41e7fa2905b3d68172ae4c05f9b3d7a2e618c45",
    contractVerified: true,
    IPFS_CID: "bafybeigrievance5107specs",
    riskScore: 24,
    bidCount: 17,
    description:
      "Multilingual grievance intake, triage and routing platform with SLA escalation and public transparency dashboards.",
    deliverables: [
      "Multilingual NLP triage engine",
      "Case routing and SLA escalation",
      "Public transparency dashboard",
    ],
    timeline: [
      { phase: "Bid window opens", date: "2026-07-20" },
      { phase: "Encrypted bid seal", date: "2026-09-02" },
      { phase: "AI risk audit", date: "2026-09-06" },
      { phase: "Allocation & payout", date: "2026-09-15" },
    ],
  },
  {
    id: "TND-6234",
    title: "Secure Tactical Comms Encryption Modules",
    issuingBody: "Directorate of Defence Acquisition",
    category: "Defense",
    budget: 1120,
    budgetCurrency: "ETH",
    deadline: "2026-11-11",
    status: "Open",
    smartContractAddr: "0x92cd034fa7b1e58630d9c72ab41f0e58c3d7a916",
    contractVerified: true,
    IPFS_CID: "bafybeicomms6234specs",
    riskScore: 36,
    bidCount: 5,
    description:
      "Supply of 12,000 hardware encryption modules with post-quantum ready key exchange for tactical radio networks.",
    deliverables: [
      "12,000 tamper-evident crypto modules",
      "Post-quantum key exchange firmware",
      "Field provisioning toolkit",
    ],
    timeline: [
      { phase: "Bid window opens", date: "2026-09-01" },
      { phase: "Encrypted bid seal", date: "2026-11-11" },
      { phase: "AI risk audit", date: "2026-11-15" },
      { phase: "Allocation & payout", date: "2026-11-28" },
    ],
  },
];

export const bids: Bid[] = [
  {
    id: "BID-8801",
    tenderId: "TND-1042",
    bidderAddress: "0x71c9e0a3b5482df6910c47bb8e2a3f5d6c0918ae",
    bidderName: "Vanta Infra Works",
    bidAmount: 1712,
    encryptedProposalHash: "0x4f1ab9...c72d",
    submissionTime: "2026-08-04T09:12:00Z",
    aiSimilarityScore: 21,
    flaggedForFraud: false,
    status: "Sealed",
    trackRecord: 88,
    ipfsCid: "bafybeiproposal8801",
  },
  {
    id: "BID-8802",
    tenderId: "TND-1042",
    bidderAddress: "0x2ac71f9b0d3e5a4876c1bb09f4e7d2a3c5081b6f",
    bidderName: "Corvus Structures Ltd",
    bidAmount: 1690,
    encryptedProposalHash: "0x9d02cc...11ba",
    submissionTime: "2026-08-05T14:41:00Z",
    aiSimilarityScore: 74,
    flaggedForFraud: true,
    status: "Under Review",
    trackRecord: 71,
    ipfsCid: "bafybeiproposal8802",
  },
  {
    id: "BID-8803",
    tenderId: "TND-1042",
    bidderAddress: "0x55b1e8c0a94d27f36b0ae1c4d97f8b02e13c6a75",
    bidderName: "Helion Civil Group",
    bidAmount: 1755,
    encryptedProposalHash: "0x77be31...0af9",
    submissionTime: "2026-08-06T07:02:00Z",
    aiSimilarityScore: 33,
    flaggedForFraud: false,
    status: "Sealed",
    trackRecord: 94,
    ipfsCid: "bafybeiproposal8803",
  },
  {
    id: "BID-8810",
    tenderId: "TND-2098",
    bidderAddress: "0x11ade9f7c3b04d258a6f1c0b7e35d94a2c8b6031",
    bidderName: "Northwind Systems",
    bidAmount: 688000,
    encryptedProposalHash: "0x1cf920...78e4",
    submissionTime: "2026-07-22T11:20:00Z",
    aiSimilarityScore: 62,
    flaggedForFraud: true,
    status: "Under Review",
    trackRecord: 65,
    ipfsCid: "bafybeiproposal8810",
  },
  {
    id: "BID-8811",
    tenderId: "TND-2098",
    bidderAddress: "0x9b71c03ae5d248f610b7ac92e4f18d05c63a7b29",
    bidderName: "Quorum Cloud Labs",
    bidAmount: 701500,
    encryptedProposalHash: "0x3ba7f1...92cd",
    submissionTime: "2026-07-25T16:05:00Z",
    aiSimilarityScore: 18,
    flaggedForFraud: false,
    status: "Sealed",
    trackRecord: 91,
    ipfsCid: "bafybeiproposal8811",
  },
  {
    id: "BID-8820",
    tenderId: "TND-3311",
    bidderAddress: "0x604fa17c9b2e35d80a1cf7be043d29561c8ba07e",
    bidderName: "Aegis Aerodyne",
    bidAmount: 2870,
    encryptedProposalHash: "0x88cd12...4fa0",
    submissionTime: "2026-08-18T08:44:00Z",
    aiSimilarityScore: 87,
    flaggedForFraud: true,
    status: "Under Review",
    trackRecord: 58,
    ipfsCid: "bafybeiproposal8820",
  },
  {
    id: "BID-8830",
    tenderId: "TND-5107",
    bidderAddress: "0x71c9e0a3b5482df6910c47bb8e2a3f5d6c0918ae",
    bidderName: "Vanta Infra Works",
    bidAmount: 249000,
    encryptedProposalHash: "0x51ea77...b3c1",
    submissionTime: "2026-07-29T10:15:00Z",
    aiSimilarityScore: 29,
    flaggedForFraud: false,
    status: "Sealed",
    trackRecord: 88,
    ipfsCid: "bafybeiproposal8830",
  },
];

export const fraudAlerts: FraudAlert[] = [
  {
    id: "ALR-501",
    tenderId: "TND-3311",
    tenderTitle: "Border Surveillance UAV Fleet Procurement",
    riskLevel: "Critical",
    detectionType: "Bid Rigging",
    description:
      "Identical technical proposal text detected across 3 distinct bidders via NLP similarity (cosine 0.94). Submission timestamps cluster within an 11-minute window from a shared /24 subnet.",
    status: "Open",
    riskScore: 92,
    detectedAt: "2026-08-19T04:11:00Z",
    vendors: ["Aegis Aerodyne", "Skyward Defence", "Orion Aeronautics"],
  },
  {
    id: "ALR-502",
    tenderId: "TND-2098",
    tenderTitle: "Sovereign Cloud Migration & Zero-Trust Rollout",
    riskLevel: "Medium",
    detectionType: "Front Running",
    description:
      "Wallet 0x11ad…6031 received a 40 ETH transfer from an address linked to the issuing authority's procurement officer 6 minutes before bid seal.",
    status: "Audit Requested",
    riskScore: 58,
    detectedAt: "2026-08-17T19:36:00Z",
    vendors: ["Northwind Systems"],
  },
  {
    id: "ALR-503",
    tenderId: "TND-1042",
    tenderTitle: "National Highway Corridor Phase III",
    riskLevel: "Medium",
    detectionType: "Bid Rigging",
    description:
      "Pricing anomaly: bid spread across 4 vendors is 0.7%, far below the 6.2% category baseline — statistically consistent with a cover-bidding cartel.",
    status: "Open",
    riskScore: 61,
    detectedAt: "2026-08-16T12:03:00Z",
    vendors: ["Corvus Structures Ltd", "Helion Civil Group"],
  },
  {
    id: "ALR-504",
    tenderId: "TND-6234",
    tenderTitle: "Secure Tactical Comms Encryption Modules",
    riskLevel: "Critical",
    detectionType: "Phantom Contractor",
    description:
      "Ghost vendor signal: company registration issued 9 days ago, no tax filings on record, wallet funded from a single mixer output. Directorship overlaps a previously debarred entity.",
    status: "Frozen",
    riskScore: 95,
    detectedAt: "2026-08-15T06:50:00Z",
    vendors: ["Pinnacle Crypto Defence LLP"],
  },
  {
    id: "ALR-505",
    tenderId: "TND-5107",
    tenderTitle: "AI Citizen Grievance Triage Platform",
    riskLevel: "Low",
    detectionType: "Front Running",
    description:
      "Minor mempool timing correlation detected between two bid transactions. Below action threshold; retained for pattern learning.",
    status: "Approved",
    riskScore: 22,
    detectedAt: "2026-08-13T21:18:00Z",
    vendors: ["Quorum Cloud Labs"],
  },
];
