import { Bid, FraudAlert, Tender } from "./types.js";

export const tendersStore: Tender[] = [
  {
    id: "TND-701",
    title: "Autonomous Drone Defence Perimeter · Zone 4",
    issuingBody: "Ministry of Infrastructure & Digital Security",
    category: "Defense",
    budget: 4500000,
    budgetCurrency: "USDT",
    deadline: "2026-09-30T23:59:59Z",
    status: "Open",
    smartContractAddr: "0x8920...3F41",
    contractVerified: true,
    IPFS_CID: "bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi",
    riskScore: 68,
    bidCount: 4,
    description: "Deploying high-speed autonomous interception drones with cryptographic telemetry.",
    deliverables: [
      "24 Autonomous ground stations",
      "Encrypted low-latency mesh communications protocol",
      "Real-time fraud audit telemetry integration",
    ],
    timeline: [
      { phase: "Sealed Bidding Window", date: "Aug 01 - Aug 30" },
      { phase: "AI Risk & ZK Audit Phase", date: "Sep 01 - Sep 10" },
      { phase: "Decentralized Escrow Payout", date: "Sep 15" },
    ],
  },
  {
    id: "TND-702",
    title: "Statewide Smart Grid IoT Telemetry Engine",
    issuingBody: "National Energy & Utility Authority",
    category: "Infrastructure",
    budget: 2800000,
    budgetCurrency: "ETH",
    deadline: "2026-10-15T23:59:59Z",
    status: "Open",
    smartContractAddr: "0x1b40...9A12",
    contractVerified: true,
    IPFS_CID: "bafybeic2h77zvhkgt7y24nf3efuylqabf3oclgtqy55fbzdi6g2234aa",
    riskScore: 24,
    bidCount: 3,
    description: "Zero-trust SCADA network sensors integrated with automated smart contract settlement.",
    deliverables: [
      "12,000 Edge IoT nodes",
      "Smart contract automated penalty triggering",
    ],
    timeline: [
      { phase: "Proposal Submission", date: "Aug 10 - Oct 01" },
      { phase: "Winner Allocation", date: "Oct 10" },
    ],
  },
  {
    id: "TND-703",
    title: "Quantum-Resistant Sovereign Cloud Backbone",
    issuingBody: "Department of Defense & Cyber Warfare",
    category: "IT",
    budget: 8900000,
    budgetCurrency: "USDT",
    deadline: "2026-08-28T23:59:59Z",
    status: "Auditing",
    smartContractAddr: "0x77c0...22B1",
    contractVerified: true,
    IPFS_CID: "bafybeid98hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi88910022a",
    riskScore: 82,
    bidCount: 5,
    description: "Post-quantum lattice-based encryption layer for inter-agency database synchronization.",
    deliverables: [
      "Hardware Security Module (HSM) deployment",
      "Lattice-based key exchange protocol",
    ],
    timeline: [
      { phase: "AI Collusion Scanning", date: "Aug 05 - Aug 25" },
      { phase: "Final Allocation", date: "Aug 28" },
    ],
  },
];

export const bidsStore: Bid[] = [
  {
    id: "BID-9011",
    tenderId: "TND-701",
    bidderAddress: "0x71C765...9B32",
    bidderName: "Pinnacle Crypto Defence LLP",
    bidAmount: 4120000,
    encryptedProposalHash: "0x8f3c12...b210",
    submissionTime: "2026-08-04T14:22:00Z",
    aiSimilarityScore: 88,
    flaggedForFraud: true,
    status: "Sealed",
    trackRecord: 54,
    ipfsCid: "bafybeia22...999a",
    proposalText: "High-speed autonomous interception drones with cryptographic telemetry mesh communications protocol.",
  },
  {
    id: "BID-9012",
    tenderId: "TND-701",
    bidderAddress: "0x3F2210...11C4",
    bidderName: "Aegis Aerodyne Systems",
    bidAmount: 4150000,
    encryptedProposalHash: "0x44a102...901f",
    submissionTime: "2026-08-04T16:05:00Z",
    aiSimilarityScore: 86,
    flaggedForFraud: true,
    status: "Sealed",
    trackRecord: 89,
    ipfsCid: "bafybeib44...888b",
    proposalText: "High-speed autonomous interception drones with cryptographic telemetry mesh communications protocol.",
  },
  {
    id: "BID-9013",
    tenderId: "TND-701",
    bidderAddress: "0x90A114...78F2",
    bidderName: "Vanta Infra Works",
    bidAmount: 3950000,
    encryptedProposalHash: "0x992b14...001e",
    submissionTime: "2026-08-05T09:12:00Z",
    aiSimilarityScore: 18,
    flaggedForFraud: false,
    status: "Sealed",
    trackRecord: 94,
    ipfsCid: "bafybeic55...777c",
    proposalText: "Independent modular architecture with redundant ground stations and quantum key distribution channels.",
  },
  {
    id: "BID-9014",
    tenderId: "TND-702",
    bidderAddress: "0x55E901...33D8",
    bidderName: "Quorum Cloud Labs",
    bidAmount: 2650000,
    encryptedProposalHash: "0x118c77...449d",
    submissionTime: "2026-08-06T11:40:00Z",
    aiSimilarityScore: 12,
    flaggedForFraud: false,
    status: "Sealed",
    trackRecord: 91,
    ipfsCid: "bafybeid66...666d",
    proposalText: "Scalable IoT telemetry streaming pipeline built with Rust edge runtimes and zero-knowledge data validation.",
  },
];

export const alertsStore: FraudAlert[] = [
  {
    id: "ALT-1042",
    tenderId: "TND-701",
    tenderTitle: "Autonomous Drone Defence Perimeter · Zone 4",
    riskLevel: "Critical",
    detectionType: "Bid Rigging",
    description: "TF-IDF Cosine text analysis identified 88% verbatim narrative match between Pinnacle Crypto Defence LLP and Aegis Aerodyne Systems.",
    status: "Open",
    riskScore: 88,
    detectedAt: "2026-08-04T16:10:00Z",
    vendors: ["Pinnacle Crypto Defence LLP", "Aegis Aerodyne Systems"],
  },
  {
    id: "ALT-1043",
    tenderId: "TND-703",
    tenderTitle: "Quantum-Resistant Sovereign Cloud Backbone",
    riskLevel: "Critical",
    detectionType: "Phantom Contractor",
    description: "Wallet graph clustering detected shared deployer 0x71C765... across 3 distinct shell bidder profiles.",
    status: "Audit Requested",
    riskScore: 92,
    detectedAt: "2026-08-05T10:15:00Z",
    vendors: ["Ghost Vendor Alpha", "Ghost Vendor Beta"],
  },
  {
    id: "ALT-1044",
    tenderId: "TND-702",
    tenderTitle: "Statewide Smart Grid IoT Telemetry Engine",
    riskLevel: "Medium",
    detectionType: "Front Running",
    description: "Mem-pool gas manipulation pattern detected 4 seconds before bidding window closure.",
    status: "Open",
    riskScore: 54,
    detectedAt: "2026-08-06T12:00:00Z",
    vendors: ["Sub-second Arbitrage Corp"],
  },
];
